<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Routing outbound project.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Pipelines.Outbound/Pipelines.Outbound.csproj" />
    <ProjectReference Include="../Reliability.Resiliency/Reliability.Resiliency.csproj" />
    <ProjectReference Include="../Observability.Instrumentation/Observability.Instrumentation.csproj" />
  </ItemGroup>

</Project>
