<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Reliability resiliency project.</Description>
  </PropertyGroup>

  <ItemGroup Condition="'$(PackOnly)' != 'true'">
    <PackageReference Include="DistributedLock.FileSystem" />
  </ItemGroup>

</Project>
