<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Packing.props" />

  <PropertyGroup>
    <Description>Messaging kafka package. [metaproject]</Description>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeReferencedProjectInPackage</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kafka.Services/Kafka.Services.csproj" />

  	<None Include="../README.md" Pack="true" PackagePath="\"/>
    <None Include="../LICENSE" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <Target Name="IncludeReferencedProjectInPackage">
    <ItemGroup>
      <!-- Include both DLL and PDB in the package output -->
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Clients.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Clients.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Envelopes.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Envelopes.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Messages.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Messages.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Services.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Kafka.Services.pdb" />
    </ItemGroup>
  </Target>

</Project>
