<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Dead letter envelope operations project.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Persistence.DeadLetterMessage/Persistence.DeadLetterMessage.csproj" />
    <ProjectReference Include="../Transport.DeadLetterEnvelope/Transport.DeadLetterEnvelope.csproj" />
    <ProjectReference Include="../Foundation.Extensions/Foundation.Extensions.csproj" />
  </ItemGroup>

</Project>
