set -euo pipefail

KAFKA_SERVER=${1:?missing server name}
KAFKA_VOTERS=${2:?missing kafka voters}
KAFKA_NODE_ID=${3:?missing node id}
KAFKA_CLUSTER_ID=${4:?missing cluster id}

echo "running ${KAFKA_SERVER} kafka container"
podman rm -f ${KAFKA_SERVER} 2> /dev/null || true;
podman run \
  -e KAFKA_NODE_ID=${KAFKA_NODE_ID} \
  -e KAFKA_LISTENERS="CONTROLLER://${KAFKA_SERVER}:9093,BROKER://${KAFKA_SERVER}:9094,EXTERNAL://${KAFKA_SERVER}:9092" \
  -e KAFKA_ADVERTISED_LISTENERS="BROKER://${KAFKA_SERVER}:9094,EXTERNAL://${KAFKA_SERVER}:9092" \
  -e KAFKA_INTER_BROKER_LISTENER_NAME="BROKER" \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT" \
  -e KAFKA_SASL_ENABLED_MECHANISMS="SCRAM-SHA-512" \
  -e KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS="SCRAM-SHA-512" \
  -e "KAFKA_LISTENER_NAME_EXTERNAL_SCRAM-SHA-512_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required;" \
  -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3 \
  -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3 \
  -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2 \
  -e KAFKA_DEFAULT_REPLICATION_FACTOR=3 \
  -e KAFKA_MIN_INSYNC_REPLICAS=2 \
  -e KAFKA_PROCESS_ROLES="broker,controller" \
  -e KAFKA_CONTROLLER_QUORUM_VOTERS="${KAFKA_VOTERS}" \
  -e KAFKA_CONTROLLER_LISTENER_NAMES="CONTROLLER" \
  -e CLUSTER_ID="${KAFKA_CLUSTER_ID}" \
  --network "${DEV_NETWORK}" --hosts-file=none --dns="${DEV_NETWORK_DNS}" -d --name "${KAFKA_SERVER}" \
  docker.io/apache/kafka:4.3.1