<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Routing inbound project.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Pipelines.Inbound/Pipelines.Inbound.csproj" />
  </ItemGroup>

</Project>
