<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Kafka messages project.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <ProjectReference Include="../Messaging.Core/Messaging.Core.csproj" />
  </ItemGroup>

</Project>
